### ISSUE TITLE
Pull jsoup from jcenter

### ISSUE THREAD

**Issue by krt16s** [fenimore/DemocracyDroid#29]
Is there a reason for `jsoup-1.8.3` being included as binary jar file instead of being pulled from jcenter/mavenCentral?

**Comment by fenimore** [comment]
Hi @krt16s ! Thanks for calling this to my attention (and actually looks like the latest update broke the scraping 🙄  -- I'll chnage it to pull from jcenter instead. I'm not sure how to do this. But I'll figure it out 😸

**Comment by fenimore** [comment]
@krt16s all fixed! I think? If it's not what you're looking for, just reopen the comment :)

Thanks for calling this to my attention fb987005c9bb16fcfdab04214cd45c0543f75375

**Comment by krt16s** [comment]
Yep, fixed. Thanks for having a look at this.
