### ISSUE TITLE
App crashes when video is selected

### ISSUE THREAD

**Issue by Mno-hime** [fenimore/DemocracyDroid#43]
Using version 3.6.1 on Nexus 5x's Android 8.1.0 and the app started crashing recently when I attempt to play video from the broadcast tab. If I don't restart the app immediately via "open app again" pop up I hear the first tunes of DN.

**Comment by Mno-hime** [comment]
Clearing cache and app data did not help.

**Comment by fenimore** [comment]
Hi @Mno-hime I think I've fixed it (I now have an 8.1 emulator for developing) -- see version 3.6.2

So i'll close the issue, but if you continue to experience problems after the version update (it might take a few hours), then please reopen it! 🙂

**Comment by Mno-hime** [comment]
It works! Thank you :-).
