### ISSUE TITLE
Link in app does not match link in repo

### ISSUE THREAD

**Issue by tian2992** [fenimore/DemocracyDroid#45]
The link on the about section leads to the broken link democracy now.

**Comment by fenimore** [comment]
Hi 😄 thanks for calling this to my attention (I see you found the repo link anyway, in the settings I imagine?) I'll fix this next release, thanks for filling the issue 👍

**Comment by fenimore** [comment]
I had forgotten about this, but it is fixed with 0472f8bf725ec26ed45d2e26375147b5abe7a56a
