### ISSUE TITLE
Democracy droid crashes when we click on stream audio

### ISSUE THREAD

**Issue by umair1209** [fenimore/DemocracyDroid#46]
#### Expected behavior
By clicking on stream audio we should be able to stream the audio online. 

#### Actual behavior
When I clicked on the menu on the right side od the video and tried to stream the audio, the application crashed. 

Also the application crashes after using it for some seconds (15 maybe) but that bug has already been reported. 

While I was able to stay on the app for some time, I managed to click on some of the options it has and everything worked fine except for stream video option. 

#### How to reproduce
- Open the app
- Click on menu on the right top corner of a particular video
- Click stream audio option
- The application will crash. 

* Application: Democracy droid v 3.6.2
* Operating system: Android 6.0.1

#### Recording Of The Bug

https://youtu.be/68LXTAotiTg

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@syedumair/democracy-droid-crashes-when-we-click-on-stream-audio">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by fenimore** [comment]
Thank you very much for the detailed bug report. I recently updated the app to 3.6.4 to fix this. 

I suspect you're using F-Droid? For some reason F-Droid hasn 't picked up the new build, I'll have to fix that. Thanks

**Comment by fenimore** [comment]
@umair1209 hey has this been fixed for you?
