### ISSUE TITLE
A layout adaptation problem

### ISSUE THREAD

**Issue by yuhuitech** [fenimore/DemocracyDroid#61]
**Describe the bug**

Dear developer!
In the process of using, I found a bug in layout / display. As shown in the figure below, on the second tab page, **texts in each cell seem to be tangled together**. This may be an adaptation problem. I suspect it is because **display and font size** are set to large **(mainly due to display size)**.
Because of some problems with my eyesight, I often use the largest font and display.
![103165857-dbaf8580-4857-11eb-9e22-120ae1901389](https://user-images.githubusercontent.com/25502419/128597553-7949a1a3-0b21-4ddf-9357-766b5c302518.png)

App version is 4.2.0, my mobile phone is Google Pixel 2, and the screen resolution setting is 1920* 1080. And **_my font size and display size are the largest ! ! !_** Also, my Android system version is 10.0.
The above is a description of the problem. The overall experience of the software is good. You can see that the design is very attentive. Thank you very much for the efforts of the developers all the time. I hope to receive a reply. Thank you so much!!

**Expected behavior**

I hope that texts in each cell would be separated, and in this circumstance, they tangled with each other.

**Steps to reproduce the behavior:**

1.use the largest font and display in the display setting
2.click the second tab
3.this error could be seen

**Screenshot**

<img src="https://user-images.githubusercontent.com/25502419/129184654-17b6f786-3e50-4ae7-b61c-9e78acc6f50b.png" alt="copy" width="250"/>

**Environment**

1. Version of DemocracyDroid : 4.2.0
2. Device : Google Pixel 2,
3. OS version : Android 10.0

**Comment by fenimore** [comment]
Thank you! I'll take a look soon, once I'm back at my computer

**Comment by fenimore** [comment]
Hi! Sorry this took so long to address, the timing was just that I was away! Thanks again for all your help, I'll close the ticket. When version 4.2.1 is released, please reopen the issue if it persists.
